version: '3.8'

services:
  fundax-hotreload:
    build:
      context: .
      dockerfile: Dockerfile.hotreload
    container_name: fundax-folio-creator-hotreload
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enable polling for file watching
    volumes:
      # Mount the source code for hot reloading
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      # Exclude node_modules from being overwritten by the host
      - /app/node_modules
    restart: unless-stopped